services:
  - type: web
    name: justconnect-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
      - key: REACT_APP_API_URL
        value: https://justconnect-o8k8.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://justconnect-o8k8.onrender.com
    headers:
      - source: "/socket.io/*"
        headers:
          - key: Connection
            value: upgrade
          - key: Upgrade
            value: websocket
    healthCheckPath: /
    buildFilter:
      paths:
        - frontend/**
      ignoredPaths:
        - "*.md"
        - ".gitignore"