# render.yaml
services:
  - type: web
    name: justconnect-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    headers:
      - key: X-Frame-Options
        value: DENY
      - key: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html