# render.yaml - Profesyonel Deployment Configuration
services:
  # Backend API Service
  - type: web
    name: justconnect-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      echo "🚀 Building backend..."
      npm ci || npm install
      npx prisma generate
      npm run build
      echo "✅ Backend build completed"
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: justconnect-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET  
        generateValue: true
      - key: FRONTEND_URL
        value: https://justconnect-frontend.onrender.com
      - key: PORT
        value: 5000

  # Frontend Static Site
  - type: web
    name: justconnect-frontend
    env: static
    region: oregon
    buildCommand: |
      echo "🎨 Building frontend..."
      if [ ! -f package-lock.json ]; then
        echo "Generating package-lock.json..."
        npm install --package-lock-only
      fi
      npm ci || npm install
      echo "Building React app..."
      npm run build
      echo "✅ Frontend build completed"
      ls -la build/
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    headers:
      - key: X-Frame-Options
        value: DENY
      - key: X-Content-Type-Options
        value: nosniff
      - key: X-XSS-Protection
        value: "1; mode=block"
      - key: Strict-Transport-Security
        value: "max-age=31536000; includeSubDomains"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://justconnect-backend.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://justconnect-backend.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
      - key: SKIP_PREFLIGHT_CHECK
        value: true

# Database
databases:
  - name: justconnect-postgres
    databaseName: justconnect_prod
    user: justconnect_user
    plan: free